export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FILTER = "FILTER";
export const FILTER2 = "FILTER2";
export const CATEGORIES_PRODUCT = "CATEGORIES_PRODUCT"
